spring:
  profiles:
    active: jasypt
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: ENC(ySNgMoOPvrKfMLSK1hUTbpFFkTVMgXsSRYRr8kbS1xMrhMp7SDXxz/58QKkMQD5+V6r+FzKXLAkjFbyosn2nM+gEEqC7k9zk6tFAqXpLFwEwrNH66IMx2NVbKllMICROxG8A+4NXsjA=)
    username: ENC(4mZJDH7II3aykj0fBZyD/w==)
    password: ENC(1+6zgAD3fKGFAUUWCzmQEQL2L2C1I3sP)
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
        initial-size: 5
        max-active: 20
        min-idle: 3
        # 配置获取连接等待超时的时间
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        max-open-prepared-statements: 20
        validation-query: SELECT now()
        validation-query-timeout: 5000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 1000

  dubbo:
    application:
      name: provider
    server: true
    registry:
      address: zookeeper://47.104.185.53:2181
    protocol:
      name: dubbo
      port: 20881

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      open-in-view: false

server:
  port: 8082
  servlet:
    context-path: /user_service

jetcache:
  statIntervalMinutes: 0
  areaInCacheName: false
  hidePackages: com.alibaba
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ENC(Sz3EmsVIefSafJEYg+/iaZmrKMRZ8oEg)
      port: 6379
      password: ENC(1+6zgAD3fKGFAUUWCzmQEQL2L2C1I3sP)